const ADD_EMPLOYEE='ADD_EMPLOYEE';
const ADD_EMPLOYEE_P='ADD_EMPLOYEE_PENDING';
const ADD_EMPLOYEE_S='ADD_EMPLOYEE_SUCCESS';
const ADD_EMPLOYEE_E='ADD_EMPLOYEE_ERROR';

export {ADD_EMPLOYEE};
export {ADD_EMPLOYEE_P};
export {ADD_EMPLOYEE_S};
export {ADD_EMPLOYEE_E};




